[package]
name = "osmos-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "*"
osmos-sim = { path = "../osmos-sim" }
getrandom = { version = "*", features = ["js"] }
serde = { version = "*", features = ["derive"] }
serde-wasm-bindgen = "*"
