[package]
name = "osmos-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
osmos-core = { path = "../osmos-core" }
osmos-ga = { path = "../osmos-ga" }
osmos-nn = { path = "../osmos-nn" }
nalgebra = "*"
rand = "*"
