[package]
name = "osmos-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
osmos-core = { path = "../osmos-core" }
osmos-nn = { path = "../osmos-nn" }
nalgebra = "0.32.2"
rand = "0.8.5"
rayon = "1.7.0"
