[package]
name = "osmos-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.1"
rand = "0.8.5"
osmos-core = { path = "../osmos-core" }
osmos-ga = { path = "../osmos-ga" }
osmos-nn = { path = "../osmos-nn" }
